name: fis
# channels:
#  - defaults
#  - conda-forge
#  - pytorch
dependencies:
- python=3

# Bare necessities
- flake8
- cython
- pandas
- xlrd
- numba
- scipy < 1.3.0
# https://github.com/statsmodels/statsmodels/issues/5747
- seaborn
- jupyterlab
# Until this is fixed https://github.com/jwkvam/jupyterlab-vim/pull/115
- simplejson
# - notebook < 5

# HTML
- lxml
- beautifulsoup4
- requests
- html5lib

# ML
# - pytorch
- scikit-learn
# - torchvision
# - gensim  # =0.12.4
# - pomegranate
- pystan

- joblib
- fastparquet
- dask
- python-snappy

# New
- altair
- pip
#- pymc3
- pip:
  # IDE tools
  - autopep8
  - black
  - flake8-mypy
  - pylint

  # Jupyter stuff
  - altair_saver
  - selenium
  - jupyter_nbextensions_configurator
  - jupytext
  - jupyterlab_code_formatter
  # - line-profiler  # doesn't work w/ 3.7
  # https://github.com/rkern/line_profiler/issues/132

  # HTML
  - requests_cache
  - redis
  - pandas_datareader
  - sqlitedict

  # TS
  # - tsfresh
  # - pyflux

  # MISC
  - fire
  - python-dotenv>=0.5.1
  - pytest
  - feather-format

  # Scipy
  - arviz
  - plotnine
  - probscale
  - feather-format
  - tqdm

  # Data
  - google-cloud-bigquery
  - pandas-gbq

# jupyter contrib nbextension install --user --skip-running-check
# jt -t grade3 -cellw '100%'

# jupyter labextension install jupyterlab_vim @jupyterlab/toc @ryantam626/jupyterlab_code_formatter


# jupyter labextension install @jupyterlab/toc
# jupyter labextension install jupyterlab_vim @jupyterlab/vega3-extension
